"""报表生成工具

提供格式化报表生成功能，支持 Markdown/HTML/PDF 格式。
"""

from typing import Dict, Any, List, Optional
from datetime import datetime
import json
import base64


def _format_table(
    data: List[Dict[str, Any]], columns: Optional[List[str]] = None
) -> str:
    """格式化数据为 Markdown 表格"""
    if not data:
        return "*No data available*"

    if columns is None:
        columns = list(data[0].keys())

    header = "| " + " | ".join(columns) + " |"
    separator = "| " + " | ".join(["---"] * len(columns)) + " |"

    rows = []
    for record in data:
        row_values = [str(record.get(col, "")) for col in columns]
        rows.append("| " + " | ".join(row_values) + " |")

    return "\n".join([header, separator] + rows)


def _format_json(data: Any) -> str:
    """格式化 JSON 数据"""
    if isinstance(data, str):
        try:
            data = json.loads(data)
        except json.JSONDecodeError:
            pass
    return json.dumps(data, indent=2, ensure_ascii=False)


def _generate_markdown_report(
    title: str, sections: List[Dict[str, Any]], metadata: Dict[str, Any]
) -> str:
    """生成 Markdown 格式报表"""
    lines = [
        f"# {title}",
        "",
        f"*Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*",
        "",
    ]

    if metadata:
        lines.extend(
            [
                "## Report Metadata",
                "",
                f"- **Task ID**: {metadata.get('task_id', 'N/A')}",
                f"- **Records**: {metadata.get('row_count', 'N/A')}",
                f"- **Execution Time**: {metadata.get('execution_time_ms', 0):.2f} ms",
                "",
            ]
        )

    for i, section in enumerate(sections, 1):
        section_type = section.get("type", "text")
        section_title = section.get("title", f"Section {i}")

        lines.append(f"## {i}. {section_title}")
        lines.append("")

        if section_type == "chart":
            chart_data = section.get("data", {})
            if isinstance(chart_data, dict):
                lines.append(f"**Chart Type**: {chart_data.get('chart_type', 'N/A')}")
                lines.append(f"**X Axis**: {chart_data.get('x_axis', 'N/A')}")
                lines.append(f"**Y Axis**: {chart_data.get('y_axis', 'N/A')}")

                image_data = chart_data.get("image_data", "")
                chart_format = chart_data.get("format", "")

                if chart_format == "ascii_markdown":
                    lines.append("")
                    lines.append("```")
                    lines.append(image_data)
                    lines.append("```")
                elif chart_format == "svg_base64":
                    lines.append(
                        f"\n*SVG chart (base64 encoded, {len(image_data)} bytes)*\n"
                    )
                elif chart_format == "svg":
                    lines.append("")
                    lines.append(image_data)
        elif section_type == "table":
            table_data = section.get("data", [])
            columns = section.get("columns")
            lines.append(_format_table(table_data, columns))
        elif section_type == "query_result":
            result_data = section.get("data", {})
            if isinstance(result_data, dict):
                lines.append(f"**SQL**: `{result_data.get('sql', 'N/A')}`")
                lines.append(f"**Rows**: {result_data.get('row_count', 0)}")
                lines.append(
                    f"**Time**: {result_data.get('execution_time_ms', 0):.2f} ms"
                )
                lines.append("")
                lines.append(_format_table(result_data.get("rows", [])))
        elif section_type == "summary":
            summary_data = section.get("data", {})
            lines.append(_format_json(summary_data))
        elif section_type == "text":
            lines.append(section.get("content", ""))

        lines.append("")

    lines.extend(["---", "*Report generated by Data Analytics MCP Server*"])

    return "\n".join(lines)


def _generate_html_report(
    title: str, sections: List[Dict[str, Any]], metadata: Dict[str, Any]
) -> str:
    """生成 HTML 格式报表"""
    html_parts = [
        "<!DOCTYPE html>",
        "<html>",
        "<head>",
        f"<title>{title}</title>",
        "<style>",
        "body { font-family: Arial, sans-serif; margin: 40px; }",
        "h1 { color: #333; border-bottom: 2px solid #4a90d9; }",
        "h2 { color: #4a90d9; margin-top: 30px; }",
        "table { border-collapse: collapse; width: 100%; margin: 20px 0; }",
        "th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }",
        "th { background-color: #4a90d9; color: white; }",
        "tr:nth-child(even) { background-color: #f2f2f2; }",
        ".metadata { background-color: #f8f9fa; padding: 15px; border-radius: 5px; }",
        ".footer { margin-top: 40px; color: #666; font-size: 12px; }",
        "pre { background-color: #f4f4f4; padding: 10px; border-radius: 5px; overflow-x: auto; }",
        "</style>",
        "</head>",
        "<body>",
        f"<h1>{title}</h1>",
        f"<p><em>Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</em></p>",
    ]

    if metadata:
        html_parts.extend(
            [
                "<div class='metadata'>",
                "<h3>Metadata</h3>",
                f"<p><strong>Task ID:</strong> {metadata.get('task_id', 'N/A')}</p>",
                f"<p><strong>Records:</strong> {metadata.get('row_count', 'N/A')}</p>",
                f"<p><strong>Execution Time:</strong> {metadata.get('execution_time_ms', 0):.2f} ms</p>",
                "</div>",
            ]
        )

    for i, section in enumerate(sections, 1):
        section_type = section.get("type", "text")
        section_title = section.get("title", f"Section {i}")

        html_parts.append(f"<h2>{i}. {section_title}</h2>")

        if section_type == "chart":
            chart_data = section.get("data", {})
            if isinstance(chart_data, dict):
                chart_format = chart_data.get("format", "")
                image_data = chart_data.get("image_data", "")

                if chart_format == "svg":
                    html_parts.append(image_data)
                elif chart_format == "svg_base64":
                    svg_data = base64.b64decode(image_data).decode()
                    html_parts.append(svg_data)
                elif chart_format == "ascii_markdown":
                    html_parts.append(f"<pre>{image_data}</pre>")
        elif section_type == "table":
            table_data = section.get("data", [])
            columns = section.get("columns")
            if columns is None and table_data:
                columns = list(table_data[0].keys())

            if columns:
                html_parts.append("<table><thead><tr>")
                html_parts.append("".join(f"<th>{col}</th>" for col in columns))
                html_parts.append("</tr></thead><tbody>")

                for row in table_data:
                    html_parts.append("<tr>")
                    html_parts.append(
                        "".join(f"<td>{row.get(col, '')}</td>" for col in columns)
                    )
                    html_parts.append("</tr>")

                html_parts.append("</tbody></table>")
        elif section_type == "text":
            html_parts.append(f"<p>{section.get('content', '')}</p>")

    html_parts.extend(
        [
            "<div class='footer'>",
            "<hr>",
            "<p>Report generated by Data Analytics MCP Server</p>",
            "</div>",
            "</body>",
            "</html>",
        ]
    )

    return "\n".join(html_parts)


def generate_report(
    title: str,
    data: Any,
    sections: Optional[List[Dict[str, Any]]] = None,
    format: str = "markdown",
    metadata: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """生成数据分析报表

    Args:
        title: 报表标题
        data: 报表数据（可以是查询结果、可视化结果或其他数据）
        sections: 报表章节配置列表，每项包含:
            - type: 章节类型 (text/table/chart/query_result/summary)
            - title: 章节标题
            - data: 章节数据
            - columns: (可选) 表格列定义
        format: 输出格式，支持 markdown/html/pdf/json
        metadata: 报表元数据

    Returns:
        包含报表内容的字典
    """
    format = format.lower()
    if format not in ["markdown", "html", "pdf", "json"]:
        return {
            "success": False,
            "error": f"Unsupported format: {format}. Supported: markdown, html, pdf, json",
        }

    sections = sections or []
    metadata = metadata or {}

    if not sections and data:
        if isinstance(data, dict):
            if "rows" in data or "columns" in data:
                sections.append(
                    {"type": "query_result", "title": "Query Results", "data": data}
                )
            elif "image_data" in data:
                sections.append(
                    {"type": "chart", "title": "Data Visualization", "data": data}
                )
            else:
                sections.append(
                    {"type": "summary", "title": "Data Summary", "data": data}
                )
        elif isinstance(data, list):
            sections.append({"type": "table", "title": "Data Table", "data": data})

    try:
        if format == "markdown":
            content = _generate_markdown_report(title, sections, metadata)
        elif format == "html":
            content = _generate_html_report(title, sections, metadata)
        elif format == "pdf":
            content = _generate_markdown_report(title, sections, metadata)
        elif format == "json":
            content = json.dumps(
                {
                    "title": title,
                    "sections": sections,
                    "metadata": metadata,
                    "generated_at": datetime.now().isoformat(),
                },
                indent=2,
                ensure_ascii=False,
            )

        return {
            "success": True,
            "title": title,
            "content": content,
            "format": format,
            "sections": sections,
            "generated_at": datetime.now().isoformat(),
            "metadata": metadata,
        }
    except Exception as e:
        return {"success": False, "error": f"Report generation error: {str(e)}"}


def create_report_from_analysis(
    query_result: Dict[str, Any],
    visualization_result: Optional[Dict[str, Any]] = None,
    title: str = "Data Analysis Report",
    format: str = "markdown",
) -> Dict[str, Any]:
    """从分析结果创建报表（便捷方法）

    Args:
        query_result: 数据库查询结果
        visualization_result: 可视化结果（可选）
        title: 报表标题
        format: 输出格式

    Returns:
        报表内容字典
    """
    sections = []

    sections.append(
        {"type": "query_result", "title": "Query Results", "data": query_result}
    )

    if visualization_result:
        sections.append(
            {
                "type": "chart",
                "title": visualization_result.get("title", "Visualization"),
                "data": visualization_result,
            }
        )

    metadata = {
        "row_count": query_result.get("row_count", 0),
        "execution_time_ms": query_result.get("execution_time_ms", 0),
        "sql": query_result.get("sql", ""),
    }

    return generate_report(title, None, sections, format, metadata)
